### PR TITLE
Use conf-libnl3

### PR DESCRIPTION
**Pull request by reynir**
Today I released conf-libnl3 https://github.com/ocaml/opam-repository/pull/17745, a virtual package for libnl3 and libnl-route3.

### CODE REVIEW

**Comment by edwintorok** [comment]
Thanks, before we merge this we probably need to add conf-libnl3 to https://github.com/xapi-project/xs-opam.
@psafont FYI the next time you update xs-opam

**Review by psafont — APPROVED** [review]

**Comment by psafont** [comment]
Thanks for the PR!

This change must be part of a tag, which then can be incorporated into xs-opam.

So let's merge this first. I'll open a PR to add both conf-libnl3 and conf-xen to xs-opam.

**Review by edwintorok — APPROVED** [review]

**Comment by lindig** [comment]
I assume we need to release a new version of xs-opam as it otherwise would not be picked up in our builds (but it would get picked up in the GH CI)

**Comment by psafont** [comment]
Since this is about opam metadata, only opam switches are affected (CI and dev environments).

I don't think releasing a new xs-opam version with this change will fix any issue.

For tracking reasons we can bump the version here and make it be reflected in xs-opam. If we don't care about the tracking we can just replace the metadata file. into xs-opam

**Pull request merged**
